"use client";

import { useState } from "react";
import { useApi } from "@/hooks/useApi";
import Badge from "@/components/ui/Badge";
import { PageLoader } from "@/components/ui/Spinner";
import { formatDateTime } from "@/lib/utils";
import { Search, Filter, KeyRound, RefreshCw } from "lucide-react";

export default function GatePassesPage() {
  const [q, setQ] = useState("");
  const [status, setStatus] = useState("");
  const [passType, setPassType] = useState("");

  const url = `/api/gate/passes?q=${encodeURIComponent(q)}&status=${status}&passType=${passType}`;
  const { data, loading, error, refetch } = useApi<{ passes: any[]; total: number }>(url);

  return (
    <div className="space-y-6">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="text-2xl font-bold text-slate-800">Gate Access Passes</h1>
          <p className="text-sm text-slate-500">
            Real-time estate gate passes generated by residents (visitors, self-exit, and re-entry).
          </p>
        </div>
        <button onClick={() => refetch()} className="btn-secondary self-start sm:self-auto">
          <RefreshCw className="h-4 w-4" /> Refresh
        </button>
      </div>

      <div className="card p-4">
        <div className="grid gap-3 sm:grid-cols-3">
          <div className="relative">
            <Search className="pointer-events-none absolute left-3 top-3 h-4 w-4 text-slate-400" />
            <input
              type="text"
              placeholder="Search code, resident, visitor..."
              value={q}
              onChange={(e) => setQ(e.target.value)}
              className="input pl-9"
            />
          </div>
          <select value={status} onChange={(e) => setStatus(e.target.value)} className="input">
            <option value="">All Statuses</option>
            <option value="ACTIVE">Active</option>
            <option value="USED">Used</option>
            <option value="EXPIRED">Expired</option>
            <option value="CANCELLED">Cancelled</option>
          </select>
          <select value={passType} onChange={(e) => setPassType(e.target.value)} className="input">
            <option value="">All Pass Types</option>
            <option value="VISITOR">Visitor Pass</option>
            <option value="RESIDENT_EXIT">Resident Exit Pass</option>
            <option value="RESIDENT_ENTRY">Resident Entry Pass</option>
            <option value="RESIDENT_ROUNDTRIP">Resident Roundtrip Pass</option>
          </select>
        </div>
      </div>

      {loading && <PageLoader />}
      {error && <p className="text-sm text-red-600">{error}</p>}

      {data && (
        <div className="card overflow-hidden">
          <div className="border-b border-slate-100 bg-slate-50/50 px-4 py-3 text-xs font-semibold text-slate-600">
            Total Passes: {data.total}
          </div>
          {data.passes.length === 0 ? (
            <div className="px-4 py-12 text-center text-sm text-slate-400">
              No gate passes found matching your filters.
            </div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-left text-sm text-slate-600">
                <thead className="border-b border-slate-200 bg-slate-50 text-xs font-semibold uppercase text-slate-500">
                  <tr>
                    <th className="px-4 py-3">Pass Code</th>
                    <th className="px-4 py-3">Type & Direction</th>
                    <th className="px-4 py-3">Holder / Purpose</th>
                    <th className="px-4 py-3">Resident & Unit</th>
                    <th className="px-4 py-3">Status</th>
                    <th className="px-4 py-3">Expires At</th>
                    <th className="px-4 py-3">Created</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {data.passes.map((p) => {
                    const isExpired = p.expiresAt && new Date(p.expiresAt).getTime() < Date.now();
                    const displayStatus = isExpired && p.status === "ACTIVE" ? "EXPIRED" : p.status;
                    const formatted =
                      p.code && p.code.length === 6
                        ? `${p.code.slice(0, 3)}-${p.code.slice(3)}`
                        : p.code;

                    return (
                      <tr key={p.id} className="hover:bg-slate-50/60">
                        <td className="px-4 py-3 font-mono font-bold text-brand-700">
                          <span className="inline-flex items-center gap-1.5 rounded bg-brand-50 px-2 py-1">
                            <KeyRound className="h-3.5 w-3.5 text-brand-600" />
                            {formatted}
                          </span>
                        </td>
                        <td className="px-4 py-3 text-xs">
                          <div className="font-semibold text-slate-800">
                            {p.passType.replace("_", " ")}
                          </div>
                          <div className="text-slate-400 capitalize">{p.direction.toLowerCase()}</div>
                        </td>
                        <td className="px-4 py-3">
                          <div className="font-medium text-slate-800">
                            {p.visitorName || p.purpose || "Resident Self-Pass"}
                          </div>
                          {p.vehiclePlate && (
                            <div className="text-xs text-slate-400">
                              Vehicle: <span className="font-mono">{p.vehiclePlate}</span>
                            </div>
                          )}
                        </td>
                        <td className="px-4 py-3">
                          <div className="font-medium text-slate-800">
                            {p.resident.firstName} {p.resident.lastName}
                          </div>
                          <div className="text-xs text-slate-500">
                            Unit {p.resident.property?.unitNumber || "N/A"}
                          </div>
                        </td>
                        <td className="px-4 py-3">
                          <Badge status={displayStatus} />
                        </td>
                        <td className="px-4 py-3 text-xs text-slate-500">
                          {formatDateTime(p.expiresAt)}
                        </td>
                        <td className="px-4 py-3 text-xs text-slate-400">
                          {formatDateTime(p.createdAt)}
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
